pipeline:
  name: test
  identifier: test
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: plan
        identifier: plan
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: TerraformPlan_1
                  identifier: TerraformPlan_1
                  spec:
                    provisionerIdentifier: main
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: connect_to_techwhisperin
                            repoName: test
                            gitFetchType: Branch
                            branch: main
                            folderPath: harness
                          type: Github
                      providerCredential:
                        type: Aws
                        spec:
                          connectorRef: connectawsaccount
                          region: ap-south-1
                          roleArn: ""
                      backendConfig:
                        type: Remote
                        spec:
                          store:
                            type: S3
                            spec:
                              connectorRef: connectawsaccount
                              bucketName: techwhisper-ami-snapshot-ebs-volume-inventory
                              region: ap-south-1
                              paths:
                                - harness/
                      secretManagerRef: harnessSecretManager
                  timeout: 10m
        tags: {}
