trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Plan
    displayName: PLAN
    jobs:
      - job:
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: 'aws-deployment'
              backendAWSBucketName: 'techwhisper-ami-snapshot-ebs-volume-inventory'
              backendAWSKey: 'file.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'plan'
              environmentServiceNameAWS: 'aws-deployment'

  - stage: Apply
    displayName: APPLY
    jobs:
      - job:
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: 'aws-deployment'
              backendAWSBucketName: 'techwhisper-ami-snapshot-ebs-volume-inventory'
              backendAWSKey: 'file.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'apply'
              environmentServiceNameAWS: 'aws-deployment'

  - stage: Destroy
    displayName: DESTROY
    jobs:
      - job:
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: 'aws-deployment'
              backendAWSBucketName: 'techwhisper-ami-snapshot-ebs-volume-inventory'
              backendAWSKey: 'file.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'destroy'
              environmentServiceNameAWS: 'aws-deployment'
